project_id = "fmizfozbyrohydcutkgg"

[functions.admin-notify]
verify_jwt = false

[functions.admin-action]
verify_jwt = false

[functions.luma-create-scene]
verify_jwt = true

[functions.luma-scene-status]
verify_jwt = true

[functions.shot-types]
verify_jwt = true

[functions.photos]
verify_jwt = true

[functions.delete-photo]
verify_jwt = true

[functions.delete-project]
verify_jwt = true

[functions.delete-scene]
verify_jwt = true