project_id = "fmizfozbyrohydcutkgg"

[functions.admin-notify]
verify_jwt = false

[functions.admin-action]
verify_jwt = false

[functions.n8n-callback]
verify_jwt = false

[functions.create-scene]
verify_jwt = true

[functions.projects-from-storage]
verify_jwt = true

[functions.photos-from-storage]
verify_jwt = true

[functions.storage-sync]
verify_jwt = true