// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmizfozbyrohydcutkgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaXpmb3pieXJvaHlkY3V0a2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzU2NzcsImV4cCI6MjA3MTc1MTY3N30.xVNzuWeMcFithMc9u9RraExhOQbjdPd16rfVKc5jxjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});